### ISSUE TITLE
Ability to pass in the Event ID

### ISSUE THREAD

**Issue by csexton** [Pecacheu/NovaLabs-Instructor-Form#1]
I have a feature request that I am hoping is pretty straight forward and will help solve some confusion with the instructors.

I would like the ability to pass in the `event_id` via a URL query parameter. This would allow us to link from [wautil](https://github.com/nova-labs/wild_apricot_python_flask_utils/)'s event page to FormBot, and hopefully remove some manual copy-n-paste steps for instructors.

**Comment by Pecacheu** [comment]
I'm not entirely sure what the wautils page is but I think I get the idea, you'd like a sort of "direct link" ability using a query parameter, so one can start filling out the form for a given class with the event ID filled out in advance, right?

That sounds like a good idea, I can look into implementing that.

**Comment by csexton** [comment]
Yes, exactly. If we can construct a URL and include the `event_id` as part of it, then that can be prepopulated. Perhaps something like tacking on a query param: `https://example.net:8020/?event=123456`

Context is useful, and a screenshot can be pretty revealing, here's the page we use to see details on the events:

![CleanShot 2021-06-14 at 14 05 11@2x](https://user-images.githubusercontent.com/16963/121938704-25166300-cd1a-11eb-91fe-38395340a636.png)

I was going to modify that page to include a link to Form Bot to take instructors directly to the page they need, with as much info prepopulated as possible. Fewer steps with the goal of fewer support requests 🎉

**Comment by Pecacheu** [comment]
Addressed in v3.1
It should be as easy as `https://forestfire.net:8020?{Event ID}`

**Comment by csexton** [comment]
This is awesome, thanks! I tested and it worked, future events AND past events 🎉 

Follow up question for ya. Normally in the url query parameters (the part after the `?` in the url) you would put names and values (e.g. `https://forestfire.net:8020?name=value`) Do you want to support that, which would allow adding other params in the future, or stick with what we have?

**Comment by Pecacheu** [comment]
That formatting seems to be the widely accepted standard for query parameters, yet it isn't actually built-in, so I'd have to implement parsing for it, complicating the code.

It would be doable but at the moment I don't anticipate needing anything else to be autofilled. In fact I had to argue with Jennifer and the others to get it as autofilled as it is. For example the host/instructor's email is autofilled if that info is available, but that isn't always (however, usually is) the same as their PayPal address, and certain instructors forget to change it. (I'd argue that's a "them" problem for having so many emails, lol)

**Comment by csexton** [comment]
That works for me, thanks.
